### ISSUE TITLE
Shared configuration directory error

### ISSUE THREAD

**Issue by Mintaka3a** [broccolai/tickets#69]
I run a number of different Paper servers all accessed via a Waterfall proxy.

With version 3 of the PureTickets plugin I enabled MySQL support and was able to create ./plugins/PureTickets/ as a shared folder accessible to all Paper servers.  This worked well and allowed the various /ticket commands to show the same information regardless of which Paper server you were actually connected to via the Waterfall proxy.

Sadly, PureTickets version 5 gets confused with this setup and fails to load/initialise correctly when the ./plugins/PureTickets directory is a symbolic link.

I now have to maintain separate but identical configuration.yml files for all of the Paper servers in my cluster. Insert sad face here.

**Comment by broccolai** [comment]
Hi, this was just fixed in configurate. Could you try the jar artifact in the latest run of [this](https://github.com/broccolai/tickets/runs/2319642202)

Please tell me if it's still not working.

**Comment by broccolai** [comment]
Sorry my bad, [this run](https://github.com/broccolai/tickets/runs/2319700937)

**Comment by Mintaka3a** [comment]
Thanks for your response.

No joy with 5.1.0 unfortunately.  Although I have MySQL configured as the data source in configuration.yml, PureTickets version 5.1.0 still creates a local storage.db file in its plugin folder.  If I run multiple Paper servers that share the same PureTickets plugin configuration folder, then all the other instances complain that the storage.db is a locked file.

Not to worry, I'll just go back to using separate ./plugins/PureTickets directories for each Paper server and just have them all point to the same MySQL database.

**Comment by broccolai** [comment]
Yeah, as far as I know h2 cannot be used by multiple processes at once, switching to the MySQL should fix that though.
