### ISSUE TITLE
org.bukkit.plugin.InvalidPluginException

### ISSUE THREAD

**Issue by Xyntexx** [broccolai/tickets#71]
When I start my server I get this error:

`org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: broccolai/tickets/bukkit/BukkitPlatform has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

Using git-paper-441

**Comment by broccolai** [comment]
Tickets requires Java 11 minimum now, I keep forgetting to put it on the spigot page. 

If you need help updating here's a good guide: [here](https://gist.github.com/Proximyst/67615353e2575a71faaff3f7ae9cc2b4)

If you still have trouble I'll help you

**Comment by Xyntexx** [comment]
Too bad I'm using a hosting service and have no power over the java version used.

**Comment by broccolai** [comment]
What host are you with? 

I might lower the requirement back down to 8 soon anyway if I decide to support Sponge.

**Comment by Xyntexx** [comment]
I'm using Skynode.pro/
I discovered I could contact support to get Java 11.
Is there something in particular that requires 11?

ma 12. huhtik. 2021 klo 19.59 Josh Taylor ***@***.***)
kirjoitti:

**Comment by broccolai** [comment]
Yeah, a couple libraries I use require Java 11. I'm also going to be changing how the http requests are done soon to use the Java 11 methods.

It's just generally nicer to develop in Java 11 than it is in 8.

Paper will also be requiring Java 11 when 1.17 comes so you'll have to update sooner or later.
