### ISSUE TITLE
Feature request: bungeecord version

### ISSUE THREAD

**Issue by Xyntexx** [broccolai/tickets#72]
A bungeeCord version would be nice that would run on the proxy directly without tweaking settings on all servers.

**Comment by broccolai** [comment]
I have proxy support nearly done, I am going to have it be installed on all servers though so I can make use of some advanced features that aren't on bungee.

If you just want to sync configs though you can use the mysql option and symlink your directory like the guy in #69, you'll have to use the build I link in the comments though.

I'll leave this open until proxy support is finished.

**Comment by Xyntexx** [comment]
Out of curiosity, what features are not on bungee?

**Comment by broccolai** [comment]
> Out of curiosity, what features are not on bungee?

Mainly teleportation and locations, which aren't hard to fix, proxies don't have a way to get offline players though which will be a bit of work for me to implement myself. You can track the progress of it here: #77 

I won't have a lot of time for a while though so i'm not sure when it'll be ready. I'm going to close this issue and track with the PR instead.

**Comment by Xyntexx** [comment]
tp might be replaceable with a tellraw command that suggests the tp command to the location and might be better for handling tp permissions and not tp people by accident that don't have tp perms.

/tellraw @a {"text":"Tiket 1 pos x y z ","color":"blue","clickEvent":{"action":"suggest_command","value":"/tp 0 0 0"},"hoverEvent":{"action":"show_text","contents":["tp to destination"]}}
