### ISSUE TITLE
plugin reload command not working 

### ISSUE THREAD

**Issue by Xyntexx** [broccolai/tickets#73]
/puretickets reload not working:
![image](https://user-images.githubusercontent.com/21282105/114454050-d72e9300-9be2-11eb-8332-f82e3b3eb65f.png)

or is the wiki out of date and reload is no more a thing? :D

**Comment by broccolai** [comment]
Yeah you're right, I hadn't updated the wiki for 5.0. 

I just updated the commands page and yeah reload is no longer a thing, for now at least.
